
import { AssessmentData, HealthScores } from '../types/assessment';

export const generateHealthReportPDF = async (assessmentData: AssessmentData) => {
  try {
    const { default: jsPDF } = await import('jspdf');
    
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let currentY = 20;

    // Helper function to add text with proper spacing and page breaks
    const addText = (text: string, x: number, y: number, options?: any) => {
      if (y > pageHeight - 20) {
        doc.addPage();
        y = 20;
        currentY = 20;
      }
      doc.text(text, x, y, options);
      return y;
    };

    // Header with new PediaPredict branding
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(26);
    doc.setTextColor(63, 81, 181);
    currentY = addText('PediaPredict', pageWidth / 2, currentY, { align: 'center' });
    currentY += 8;
    
    doc.setFontSize(20);
    currentY = addText('Student Obesity Risk Report', pageWidth / 2, currentY, { align: 'center' });
    currentY += 8;
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    currentY = addText('Generated by PediaPredict AI Engine', pageWidth / 2, currentY, { align: 'center' });
    currentY += 15;
    
    // Generation timestamp
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-GB', { 
      day: 'numeric', 
      month: 'long', 
      year: 'numeric' 
    });
    const timeStr = now.toLocaleTimeString('en-GB', { 
      hour: '2-digit', 
      minute: '2-digit',
      hour12: false 
    });
    doc.setFontSize(12);
    currentY = addText(`Report Generated: ${dateStr} at ${timeStr}`, pageWidth / 2, currentY, { align: 'center' });
    currentY += 15;

    // Separator line
    doc.setLineWidth(0.5);
    doc.setDrawColor(63, 81, 181);
    doc.line(20, currentY, pageWidth - 20, currentY);
    currentY += 15;

    // Student Information
    doc.setTextColor(63, 81, 181);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    currentY = addText('Student Information', 20, currentY);
    currentY += 10;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    // Safe data extraction with proper null checks
    const socioDemo = assessmentData.socioDemographic;
    const studentInfo = [
      `Name: ${socioDemo?.name || 'Not Provided'}`,
      `Age: ${socioDemo?.age || 'Not Provided'} years`,
      `Gender: ${socioDemo?.gender ? socioDemo.gender.charAt(0).toUpperCase() + socioDemo.gender.slice(1) : 'Not Provided'}`,
      `Class: ${socioDemo?.class || 'Not Provided'}-${socioDemo?.section || 'Not Provided'}`,
      `School: ${socioDemo?.schoolName || 'Not Provided'}`,
      `Assessment Date: ${assessmentData.completedAt ? new Date(assessmentData.completedAt).toLocaleDateString('en-GB') : 'Not Available'}`,
      `BMI: ${assessmentData.bmi ? assessmentData.bmi.toFixed(1) : 'Not Calculated'} (${getBMICategory(assessmentData.bmi || 0)})`
    ];

    studentInfo.forEach((info) => {
      currentY = addText(info, 20, currentY);
      currentY += 6;
    });
    currentY += 15;

    // Obesity Risk Assessment (Main Section)
    doc.setLineWidth(0.3);
    doc.line(20, currentY, pageWidth - 20, currentY);
    currentY += 10;

    const riskLevel = assessmentData.aiPrediction?.riskLevel || 'Medium';
    doc.setTextColor(63, 81, 181);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    currentY = addText('Obesity Risk Report', 20, currentY);
    currentY += 10;

    // Risk Level with color coding
    const riskColor = riskLevel === 'High' ? [220, 53, 69] : 
                     riskLevel === 'Medium' ? [255, 193, 7] : [40, 167, 69];
    doc.setTextColor(...riskColor);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    currentY = addText(`OBESITY RISK LEVEL: ${riskLevel.toUpperCase()}`, 20, currentY);
    currentY += 15;

    // Assessment Categories
    doc.setTextColor(63, 81, 181);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    currentY = addText('Assessment Categories', 20, currentY);
    currentY += 10;

    // Safe scores handling - removed score display as requested
    const defaultScores: HealthScores = {
      eatingHabitsScore: 0,
      physicalActivityScore: 0,
      sedentaryScore: 0,
      mentalHealthScore: 0,
      sleepScore: 0
    };
    
    const scores: HealthScores = { ...defaultScores, ...assessmentData.scores };
    
    const categoryItems = [
      'BMI Assessment',
      'Nutrition Habits',
      'Physical Activity',
      'Screen Time Management',
      'Sleep Quality',
      'Mental Health & Wellbeing'
    ];

    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);

    categoryItems.forEach((item) => {
      currentY = addText(`• ${item}: Assessed`, 25, currentY);
      currentY += 6;
    });
    currentY += 15;

    // Recommendations
    doc.setLineWidth(0.3);
    doc.line(20, currentY, pageWidth - 20, currentY);
    currentY += 10;

    doc.setTextColor(40, 167, 69);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    currentY = addText('PediaPredict AI Recommendations', 20, currentY);
    currentY += 10;

    const recommendations = assessmentData.aiPrediction?.recommendations || [
      'Maintain regular physical activity for at least 60 minutes daily',
      'Include more fruits and vegetables in daily meals',
      'Limit recreational screen time to less than 2 hours per day',
      'Ensure 8-9 hours of quality sleep each night',
      'Practice stress management and maintain positive mental health'
    ];

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    recommendations.slice(0, 5).forEach((rec, index) => {
      currentY = addText(`${index + 1}. ${rec}`, 25, currentY);
      currentY += 6;
    });
    currentY += 20;

    // Footer with new branding
    doc.setLineWidth(0.3);
    doc.line(20, currentY, pageWidth - 20, currentY);
    currentY += 10;

    doc.setTextColor(63, 81, 181);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    currentY = addText('PediaPredict | Confidential Student Obesity Risk Report', pageWidth / 2, currentY, { align: 'center' });
    currentY += 5;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    currentY = addText('Powered by Doutly Technologies | www.pediapredict.in', pageWidth / 2, currentY, { align: 'center' });
    currentY += 4;
    currentY = addText('© 2025 | All Rights Reserved', pageWidth / 2, currentY, { align: 'center' });

    // Generate safe filename with PediaPredict branding
    const cleanName = (socioDemo?.name || 'student').replace(/[^a-zA-Z0-9]/g, '_');
    const dateStr2 = now.toISOString().split('T')[0];
    const timeStamp = now.toTimeString().split(' ')[0].replace(/:/g, '-');
    const filename = `pediapredict_obesity_risk_${cleanName}_${dateStr2}_${timeStamp}.pdf`;
    
    // Save the PDF
    doc.save(filename);

    return true;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF report. Please check your data and try again.');
  }
};

// Helper function for BMI categorization
function getBMICategory(bmi: number): string {
  if (bmi < 18.5) return 'Underweight';
  if (bmi < 25) return 'Normal Weight';
  if (bmi < 30) return 'Overweight';
  return 'Obese';
}
